[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
vault_acc = "9pU1ESxdgeWPKjQwg6R7vuVom8rno7L8CNb76EUh6vVN"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/samyakt/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
